//<![CDATA[
$(document).ready(function(){ 
$('a[name="details1"]').before($('#Theme-details1').html()); 
$('#Theme-details1').html(''); 
}); 
//
$(document).ready(function(){ 
$('a[name="details2"]').before($('#Theme-details2').html()); 
$('#Theme-details2').html(''); 
});
//
$(document).ready(function(){ 
$('a[name="details3"]').before($('#Theme-details3').html()); 
$('#Theme-details3').html(''); 
});
//
$(document).ready(function(){ 
$('a[name="details4"]').before($('#Theme-details4').html()); 
$('#Theme-details4').html(''); 
});
//]]>
